// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DistrictController from "./district_controller"
application.register("district", DistrictController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)


import IssuesController from "./issues_controller"
application.register("issues", IssuesController)