services:
  - type: web
    name: dehradun-feedback
    env: ruby
    plan: free
    region: oregon
    buildCommand: |
      bundle install
      yarn install --frozen-lockfile || yarn install
      bundle exec rake assets:precompile
    startCommand: bundle exec rails server -p $PORT -e production
    postDeployCommand: bundle exec rails db:migrate
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "1"
      - key: RAILS_SERVE_STATIC_FILES
        value: "1"
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: dehradun-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: dehradun-db
    plan: free
    region: oregon
